version: '3.2'
services:
    frontend:
        container_name: frontend_v2
        image: aergoscan/frontend:2.4.0
        ports:
            - '80:80'
        build:
            args:
                ARG_AERGO_NODE: ${AERGO_NODE}
                ARG_API_URL: ${SCAN_API_HOST}/v2
            dockerfile: Dockerfile.ip
        depends_on:
            - backend
    backend:
        container_name: aergoscan-api
        image: aergoscan/api:2.4.0
        ports:
            - '3000:3000'
        build:
            context: ./aergoscan_v2_api
        environment:
            HOST_API: ${SCAN_API_HOST}
            SELECTED_NETWORK: local
            ES_URL: es:9200
            HTTP_PORT: 3000
        depends_on:
            - db
        restart: always
    indexer:
        container_name: indexer
        image: aergo/indexer2:2.4.0
        ports:
            - 8000:8000
        privileged: true
        command: indexer
            - --aergo=${AERGO_NODE}
            - --dburl=es:9200
            - --prefix=local
            - --mode=all
            - --from=0
            - --to=0
        depends_on:
            - db
        restart: always
    db:
        container_name: es
        image: docker.elastic.co/elasticsearch/elasticsearch:7.15.2
        environment:
            discovery.type: single-node
            xpack.security.enabled: false
            bootstrap.memory_lock: true
            ES_JAVA_OPTS: -Xms1024m -Xmx1024m
        ulimits:
            memlock:
                soft: -1
                hard: -1
        volumes:
            - type: bind
              source: ./data/eldata/data # custom
              target: /usr/share/elasticsearch/data
            - type: bind
              source: ./data/eldata/logs # custom
              target: /usr/share/elasticsearch/logs
        ports:
            - 9200:9200
            - 9300:9300
        privileged: true
        logging:
            driver: 'json-file'
            options:
                max-file: '7'
                max-size: '1000m'
    # 키바나 조회 필요 시 주석 해제
    # kibana:
    #     image: docker.elastic.co/kibana/kibana:7.15.2
    #     container_name: kibana
    #     ports:
    #         - 5601:5601
    #     environment:
    #         ELASTICSEARCH_URL: http://es:9200
    #         ELASTICSEARCH_HOSTS: http://es:9200
    #     logging:
    #         driver: 'json-file'
    #         options:
    #             max-file: '7'
    #             max-size: '1000m'
    #     depends_on:
    #         - db
