version: "3.2"
services:
  backend:
    image: aergoscan/api:2.1.1
    ports:
      - "3000:3000"
    build:
      context: ./aergoscan_v2_api
      args:
        ARG_SELECTED_NETWORK: local
        ARG_ES_URL: local.aergoscan.io:9200
        ARG_HTTP_PORT: 3000
    restart: always
    privileged: true
    command:
      - sudo docker run -d --rm -p 3000:3000 --net=host --privileged --name aergoscan-api aergoscan/api:2.1.1
  frontend:
    image: aergoscan/frontend:2.0.0
    ports:
      - "80:80"
      - "443:443"
    build:
      context: ./aergoscan_v2_frontend
      args:
        ARG_AERGO_NODE: https://local.aergoscan.io/ws
        ARG_API_URL: https://localapi.aergoscan.io/testnet
